version: "3.9"

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: travel
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - "3002:3002"
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/travel?sslmode=disable
      - JWT_SECRET=supersecretjwt123
    command: ["/app/travel-go"]
    working_dir: /app


volumes:
  db_data:
